apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.fullName}}-service
  labels:
    app: {{.Values.app.fullName}}-service
spec:
  type: ClusterIP
  selector:
    app: {{.Values.app.fullName}}
  ports:
    - name: http
      port: 8080
      targetPort: {{.Values.container.port}}
      protocol: TCP

